import { randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'

test('flujo real: registro → login → mascota → cita → cancelación → cierre', async ({ page }, testInfo) => {
  const email = `review-${randomUUID()}@example.com`
  const password = `Review-${randomUUID()}`
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  // A 401 after deliberately revisiting a protected route without a session is expected.
  page.on('console', message => {
    if (message.type() === 'error' && !message.text().includes('status of 401')) errors.push(message.text())
  })
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const screenshot = async (name: string) => { await noOverflow(); await page.screenshot({ path: testInfo.outputPath(`${name}.png`), fullPage: true }) }
  const navigate = async (name: string) => {
    const menu = page.getByRole('button', { name: 'Abrir menú' })
    if (await menu.isVisible()) await menu.click()
    await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('link', { name, exact: true }).click()
  }
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Más tiempo juntos/ })).toBeVisible()
  await screenshot('01-inicio')
  await page.getByRole('link', { name: 'Crear cuenta', exact: true }).click()
  await page.getByLabel('Nombres').fill('Ana')
  await page.getByLabel('Apellidos').fill('Torres')
  await page.getByLabel('Correo electrónico').fill(email)
  await page.getByLabel('Teléfono').fill('987654321')
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByLabel('Confirmar contraseña').fill(password)
  await screenshot('02-registro')
  await page.getByRole('button', { name: 'Crear mi cuenta' }).click()
  await expect(page).toHaveURL(/iniciar-sesion/)
  await expect(page.getByRole('status')).toContainText('Tu cuenta está lista')
  await page.getByLabel('Correo electrónico').fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Iniciar sesión' }).click()
  await expect(page.getByRole('heading', { name: 'Hola, Ana 👋' })).toBeVisible()
  await screenshot('03-panel-vacio')
  await page.getByRole('link', { name: 'Registrar mascota', exact: true }).click()
  await page.getByLabel('Nombre', { exact: true }).fill('Luna')
  await page.getByLabel('Especie').selectOption('Gato')
  await page.getByLabel('Raza').fill('Mestizo')
  await page.getByLabel('Sexo').selectOption('Hembra')
  await page.getByLabel('Fecha de nacimiento aproximada').fill('2022-03-12')
  await page.getByLabel('Peso (kg)').fill('4.5')
  await page.getByLabel('Color').fill('Gris')
  await page.getByRole('button', { name: 'Registrar mascota' }).click()
  await expect(page.getByRole('heading', { name: 'Conoce a Luna' })).toBeVisible()
  const petUrl = page.url()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Conoce a Luna' })).toBeVisible()
  await screenshot('04-mascota')
  await page.getByRole('link', { name: 'Editar datos' }).click()
  await page.getByLabel('Peso (kg)').fill('4.8')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByText('4.8 kg', { exact: true })).toBeVisible()
  await navigate('Veterinarias')
  await page.getByLabel('Buscar veterinaria por nombre').fill('Miraflores')
  await expect(page.getByRole('heading', { name: 'VetGest Miraflores', exact: true })).toBeVisible()
  await screenshot('05-veterinarias')
  await page.getByRole('link', { name: 'Ver servicios' }).click()
  await expect(page.getByRole('heading', { name: 'Servicios disponibles' })).toBeVisible()
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Consulta general', exact: true }) }).getByRole('link', { name: 'Solicitar cita' }).click()
  await page.getByLabel('Mascota', { exact: true }).selectOption({ label: 'Luna · Gato' })
  const tomorrow = new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10)
  await page.getByLabel('Fecha', { exact: true }).fill(tomorrow)
  await page.getByLabel('Hora (Lima, UTC−5)').fill('10:00')
  await page.getByLabel('Motivo o comentario (opcional)').fill('Control preventivo de Luna.')
  await screenshot('06-solicitud')
  await page.getByRole('button', { name: 'Solicitar cita', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Tu solicitud se registró correctamente')
  await screenshot('07-cita-pendiente')
  await page.getByRole('button', { name: 'Cancelar cita', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Sí, cancelar cita' }).click()
  await expect(page.getByRole('status')).toContainText('Tu cita se canceló correctamente')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await navigate('Mi perfil')
  await page.getByLabel('Teléfono').fill('912345678')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('status')).toContainText('Tus datos se guardaron')
  await screenshot('08-perfil')
  await page.goto(petUrl)
  await page.getByRole('button', { name: 'Eliminar mascota' }).click()
  await page.getByRole('button', { name: 'Sí, eliminar mascota' }).click()
  await expect(page.getByRole('heading', { name: 'Todavía no tienes mascotas registradas' })).toBeVisible()
  if (await page.getByRole('button', { name: 'Abrir menú' }).isVisible()) await page.getByRole('button', { name: 'Abrir menú' }).click()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page).toHaveURL(/iniciar-sesion/)
  await page.goto('/app/mascotas')
  await expect(page).toHaveURL(/iniciar-sesion/)
  expect(errors).toEqual([])
})
